#ifndef DEFINES_H
#define DEFINES_H

#define CELL_OK 0
#define CELL_STATUS_IS_FAILURE(status) ((status) & 0x80000000)
#define CELL_STATUS_IS_SUCCESS(status) (!(CELL_STATUS_IS_FAILURE))

#define CELL_LV2DBG_ERROR_DEINVALIDPROCESSID		  (0x80010401)
#define CELL_LV2DBG_ERROR_DEINVALIDTHREADID			  (0x80010402)
#define CELL_LV2DBG_ERROR_DEILLEGALREGISTERTYPE		  (0x80010403)
#define CELL_LV2DBG_ERROR_DEILLEGALREGISTERNUMBER	  (0x80010404)
#define CELL_LV2DBG_ERROR_DEILLEGALTHREADSTATE		  (0x80010405)
#define CELL_LV2DBG_ERROR_DEINVALIDEFFECTIVEADDRESS	  (0x80010406)
#define CELL_LV2DBG_ERROR_DENOTFOUNDPROCESSID		  (0x80010407)
#define CELL_LV2DBG_ERROR_DENOMEM			          (0x80010408)
#define CELL_LV2DBG_ERROR_DEINVALIDARGUMENTS		  (0x80010409)
#define CELL_LV2DBG_ERROR_DENOTFOUNDFILE		      (0x8001040a)
#define CELL_LV2DBG_ERROR_DEINVALIDFILETYPE		      (0x8001040b)
#define CELL_LV2DBG_ERROR_DENOTFOUNDTHREADID		  (0x8001040c)
#define CELL_LV2DBG_ERROR_DEINVALIDTHREADSTATUS		  (0x8001040d)
#define CELL_LV2DBG_ERROR_DENOAVAILABLEPROCESSID	  (0x8001040e)
#define CELL_LV2DBG_ERROR_DENOTFOUNDEVENTHANDLER	  (0x8001040f)
#define CELL_LV2DBG_ERROR_DESPNOROOM				  (0x80010410)
#define CELL_LV2DBG_ERROR_DESPNOTFOUND				  (0x80010411)
#define CELL_LV2DBG_ERROR_DESPINPROCESS				  (0x80010412)
#define CELL_LV2DBG_ERROR_DEINVALIDPRIMARYSPUTHREADID (0x80010413)
#define CELL_LV2DBG_ERROR_DETHREADSTATEISNOTSTOPPED	  (0x80010414)
#define CELL_LV2DBG_ERROR_DEINVALIDTHREADTYPE		  (0x80010415)
#define CELL_LV2DBG_ERROR_DECONTINUEFAILED		      (0x80010416)
#define CELL_LV2DBG_ERROR_DESTOPFAILED			      (0x80010417)
#define CELL_LV2DBG_ERROR_DENOEXCEPTION			      (0x80010418)
#define CELL_LV2DBG_ERROR_DENOMOREEVENTQUE		      (0x80010419)
#define CELL_LV2DBG_ERROR_DEEVENTQUENOTCREATED		  (0x8001041a)
#define CELL_LV2DBG_ERROR_DEEVENTQUEOVERFLOWED		  (0x8001041b)
#define CELL_LV2DBG_ERROR_DENOTIMPLEMENTED		      (0x8001041c)
#define CELL_LV2DBG_ERROR_DEQUENOTREGISTERED		  (0x8001041d)
#define CELL_LV2DBG_ERROR_DENOMOREEVENTPROCESS		  (0x8001041e)
#define CELL_LV2DBG_ERROR_DEPROCESSNOTREGISTERED	  (0x8001041f)
#define CELL_LV2DBG_ERROR_DEEVENTDISCARDED			  (0x80010420)
#define CELL_LV2DBG_ERROR_DENOMORESYNCID			  (0x80010421)
#define CELL_LV2DBG_ERROR_DESYNCIDALREADYADDED		  (0x80010422)
#define CELL_LV2DBG_ERROR_DESYNCIDNOTFOUND			  (0x80010423)
#define CELL_LV2DBG_ERROR_DESYNCIDNOTACQUIRED		  (0x80010424)
#define CELL_LV2DBG_ERROR_DEPROCESSALREADYREGISTERED  (0x80010425)
#define CELL_LV2DBG_ERROR_DEINVALIDLSADDRESS		  (0x80010426)
#define CELL_LV2DBG_ERROR_DEINVALIDOPERATION		  (0x80010427)
#define CELL_LV2DBG_ERROR_DEINVALIDMODULEID			  (0x80010428)
#define CELL_LV2DBG_ERROR_DEHANDLERALREADYREGISTERED  (0x80010429)
#define CELL_LV2DBG_ERROR_DEINVALIDHANDLER		      (0x8001042a)
#define CELL_LV2DBG_ERROR_DEHANDLENOTREGISTERED		  (0x8001042b)
#define CELL_LV2DBG_ERROR_DEOPERATIONDENIED			  (0x8001042c)
#define CELL_LV2DBG_ERROR_DEHANDLERNOTINITIALIZED	  (0x8001042d)
#define CELL_LV2DBG_ERROR_DEHANDLERALREADYINITIALIZED (0x8001042e)
#define CELL_LV2DBG_ERROR_DEILLEGALCOREDUMPPARAMETER  (0x8001042f)


#define MAX_NUM_OF_SYSTEM_CALLS                            1024

#define SYS_PROCESS_GETPID                                    1
#define SYS_PROCESS_WAIT_FOR_CHILD                            2
#define SYS_PROCESS_GET_STATUS                                4
#define SYS_PROCESS_DETACH_CHILD                              5
#define SYS_PROCESS_GET_NUMBER_OF_OBJECT                     12
#define SYS_PROCESS_GET_ID                                   13
#define SYS_PROCESS_IS_SPU_LOCK_LINE_RESERVATION_ADDRESS     14
#define SYS_PROCESS_GETPPID                                  18
#define SYS_PROCESS_KILL                                     19
#define SYS_PROCESS_WAIT_FOR_CHILD2                          23
#define SYS_PROCESS_GET_SDK_VERSION                          25
#define SYS_PROCESS_GET_PPU_GUID                             31
#define SYS_PROCESS_EXIT									  3
#define SYS_PROCESS_SPAWN								     21
#define SYS_PROCESS_GET_PARAMSFO							 30
#define SYSCALL_PROCESS_GETPID                               SYS_PROCESS_GETPID
#define SYSCALL_PROCESS_WAIT_FOR_CHILD                       SYS_PROCESS_WAIT_FOR_CHILD
#define SYSCALL_PROCESS_GET_STATUS                           SYS_PROCESS_GET_STATUS
#define SYSCALL_PROCESS_DETACH_CHILD                         SYS_PROCESS_DETACH_CHILD
#define SYSCALL_PROCESS_GET_NUMBER_OF_OBJECT                 SYS_PROCESS_GET_NUMBER_OF_OBJECT
#define SYSCALL_PROCESS_GET_ID                               SYS_PROCESS_GET_ID
#define SYSCALL_PROCESS_IS_SPU_LOCK_LINE_RESERVATION_ADDRESS SYS_PROCESS_IS_SPU_LOCK_LINE_RESERVATION_ADDRESS
#define SYSCALL_PROCESS_GETPPID                              SYS_PROCESS_GETPPID
#define SYSCALL_PROCESS_KILL                                 SYS_PROCESS_KILL
#define SYSCALL_PROCESS_WAIT_FOR_CHILD2                      SYS_PROCESS_WAIT_FOR_CHILD2
#define SYSCALL_PROCESS_GET_SDK_VERSION                      SYS_PROCESS_GET_SDK_VERSION
#define SYSCALL_PROCESS_GET_PPU_GUID                         SYS_PROCESS_GET_PPU_GUID
#define SYSCALL_PROCESS_EXIT								 SYS_PROCESS_EXIT
#define SYSCALL_PROCESS_SPAWN								 SYS_PROCESS_SPAWN
#define SYSCALL_PROCESS_GET_PARAMSFO						 SYS_PROCESS_GET_PARAMSFO

#define SYS_PPU_THREAD_YIELD                               43
#define SYS_PPU_THREAD_JOIN                                44
#define SYS_PPU_THREAD_DETACH                              45
#define SYS_PPU_THREAD_GET_JOIN_STATE                      46
#define SYS_PPU_THREAD_SET_PRIORITY                        47
#define SYS_PPU_THREAD_GET_PRIORITY                        48
#define SYS_PPU_THREAD_GET_STACK_INFORMATION               49
#define SYS_PPU_THREAD_RENAME                              56
#define SYS_PPU_THREAD_RECOVER_PAGE_FAULT                  57
#define SYS_PPU_THREAD_GET_PAGE_FAULT_CONTEXT              58
#define SYS_PPU_THREAD_EXIT								   41
#define SYS_PPU_THREAD_STOP								   50
#define SYS_PPU_THREAD_RESTART							   51
#define SYS_PPU_THREAD_CREATE							   52
#define SYS_PPU_THREAD_START							   53
#define SYS_PPU_THREAD_GET_ID							   42
#define SYSCALL_PPU_THREAD_YIELD                  		   SYS_PPU_THREAD_YIELD
#define SYSCALL_PPU_THREAD_JOIN                   		   SYS_PPU_THREAD_JOIN
#define SYSCALL_PPU_THREAD_DETACH                 		   SYS_PPU_THREAD_DETACH
#define SYSCALL_PPU_THREAD_GET_JOIN_STATE         		   SYS_PPU_THREAD_GET_JOIN_STATE
#define SYSCALL_PPU_THREAD_SET_PRIORITY           		   SYS_PPU_THREAD_SET_PRIORITY
#define SYSCALL_PPU_THREAD_GET_PRIORITY           		   SYS_PPU_THREAD_GET_PRIORITY
#define SYSCALL_PPU_THREAD_GET_STACK_INFORMATION  		   SYS_PPU_THREAD_GET_STACK_INFORMATION
#define SYSCALL_PPU_THREAD_RENAME                 		   SYS_PPU_THREAD_RENAME
#define SYSCALL_PPU_THREAD_RECOVER_PAGE_FAULT     		   SYS_PPU_THREAD_RECOVER_PAGE_FAULT
#define SYSCALL_PPU_THREAD_GET_PAGE_FAULT_CONTEXT 		   SYS_PPU_THREAD_GET_PAGE_FAULT_CONTEXT
#define SYSCALL_PPU_THREAD_EXIT 		   				   SYS_PPU_THREAD_EXIT
#define SYSCALL_PPU_THREAD_STOP 		   				   SYS_PPU_THREAD_STOP
#define SYSCALL_PPU_THREAD_RESTART 		   				   SYS_PPU_THREAD_RESTART
#define SYSCALL_PPU_THREAD_CREATE 		   				   SYS_PPU_THREAD_CREATE
#define SYSCALL_PPU_THREAD_START 		   				   SYS_PPU_THREAD_START
#define SYSCALL_PPU_THREAD_GET_ID 		   				   SYS_PPU_THREAD_GET_ID

#define SYS_TRACE_ALLOCATE_BUFFER                          67
#define SYS_TRACE_FREE_BUFFER                              68
#define SYS_TRACE_CREATE2                                  69
#define SYS_TRACE_CREATE2_IN_CBEPM                         77
#define SYSCALL_TRACE_ALLOCATE_BUFFER                      SYS_TRACE_ALLOCATE_BUFFER
#define SYSCALL_TRACE_FREE_BUFFER                          SYS_TRACE_FREE_BUFFER
#define SYSCALL_TRACE_CREATE2                              SYS_TRACE_CREATE2
#define SYSCALL_TRACE_CREATE2_IN_CBEPM                     SYS_TRACE_CREATE2_IN_CBEPM

#define SYS_TIMER_CREATE                                   70
#define SYS_TIMER_DESTROY                                  71
#define SYS_TIMER_GET_INFORMATION                          72
#define SYS_TIMER_STOP                                     74
#define SYS_TIMER_CONNECT_EVENT_QUEUE                      75
#define SYS_TIMER_DISCONNECT_EVENT_QUEUE                   76
#define SYS_TIMER_USLEEP                                  141
#define SYS_TIMER_SLEEP                                   142
#define SYS_TIMER_START									   73
#define SYSCALL_TIMER_CREATE                               SYS_TIMER_CREATE
#define SYSCALL_TIMER_DESTROY                              SYS_TIMER_DESTROY
#define SYSCALL_TIMER_GET_INFORMATION                      SYS_TIMER_GET_INFORMATION
#define SYSCALL_TIMER_STOP                                 SYS_TIMER_STOP
#define SYSCALL_TIMER_CONNECT_EVENT_QUEUE                  SYS_TIMER_CONNECT_EVENT_QUEUE
#define SYSCALL_TIMER_DISCONNECT_EVENT_QUEUE               SYS_TIMER_DISCONNECT_EVENT_QUEUE
#define SYSCALL_TIMER_USLEEP                               SYS_TIMER_USLEEP
#define SYSCALL_TIMER_SLEEP                                SYS_TIMER_SLEEP
#define SYSCALL_TIMER_START								   SYS_TIMER_START

#define SYS_INTERRUPT_TAG_CREATE                           80
#define SYS_INTERRUPT_TAG_DESTROY                          81
#define SYS_INTERRUPT_THREAD_EOI                           88
#define SYS_INTERRUPT_THREAD_ESTABLISH                     84
#define SYS_INTERRUPT_THREAD_DISESTABLISH                  89
#define SYSCALL_INTERRUPT_THREAD_ESTABLISH                 SYS_INTERRUPT_THREAD_ESTABLISH
#define SYSCALL_INTERRUPT_THREAD_DISESTABLISH              SYS_INTERRUPT_THREAD_DISESTABLISH
#define SYSCALL_INTERRUPT_TAG_CREATE                       SYS_INTERRUPT_TAG_CREATE
#define SYSCALL_INTERRUPT_TAG_DESTROY                      SYS_INTERRUPT_TAG_DESTROY
#define SYSCALL_INTERRUPT_THREAD_EOI                       SYS_INTERRUPT_THREAD_EOI

#define SYS_SEMAPHORE_CREATE                               90
#define SYS_SEMAPHORE_DESTROY                              91
#define SYS_SEMAPHORE_WAIT                                 92
#define SYS_SEMAPHORE_TRYWAIT                              93
#define SYS_SEMAPHORE_POST                                 94
#define SYS_SEMAPHORE_GET_VALUE                           114
#define SYSCALL_SEMAPHORE_CREATE                          SYS_SEMAPHORE_CREATE
#define SYSCALL_SEMAPHORE_DESTROY                         SYS_SEMAPHORE_DESTROY
#define SYSCALL_SEMAPHORE_WAIT                            SYS_SEMAPHORE_WAIT
#define SYSCALL_SEMAPHORE_TRYWAIT                         SYS_SEMAPHORE_TRYWAIT
#define SYSCALL_SEMAPHORE_POST                            SYS_SEMAPHORE_POST
#define SYSCALL_SEMAPHORE_GET_VALUE                       SYS_SEMAPHORE_GET_VALUE

#define SYS_MUTEX_CREATE                                  100
#define SYS_MUTEX_DESTROY                                 101
#define SYS_MUTEX_LOCK                                    102
#define SYS_MUTEX_TRYLOCK                                 103
#define SYS_MUTEX_UNLOCK                                  104
#define SYSCALL_MUTEX_CREATE                              SYS_MUTEX_CREATE
#define SYSCALL_MUTEX_DESTROY                             SYS_MUTEX_DESTROY
#define SYSCALL_MUTEX_LOCK                                SYS_MUTEX_LOCK
#define SYSCALL_MUTEX_TRYLOCK                             SYS_MUTEX_TRYLOCK
#define SYSCALL_MUTEX_UNLOCK                              SYS_MUTEX_UNLOCK

#define SYS_COND_CREATE                                   105
#define SYS_COND_DESTROY                                  106
#define SYS_COND_WAIT                                     107
#define SYS_COND_SIGNAL                                   108
#define SYS_COND_SIGNAL_ALL                               109
#define SYS_COND_SIGNAL_TO                                110
#define SYSCALL_COND_CREATE                               SYS_COND_CREATE
#define SYSCALL_COND_DESTROY                              SYS_COND_DESTROY
#define SYSCALL_COND_WAIT                                 SYS_COND_WAIT
#define SYSCALL_COND_SIGNAL                               SYS_COND_SIGNAL
#define SYSCALL_COND_SIGNAL_ALL                           SYS_COND_SIGNAL_ALL
#define SYSCALL_COND_SIGNAL_TO                            SYS_COND_SIGNAL_TO

#define SYS_RWLOCK_CREATE                                 120
#define SYS_RWLOCK_DESTROY                                121
#define SYS_RWLOCK_RLOCK                                  122
#define SYS_RWLOCK_TRYRLOCK                               123
#define SYS_RWLOCK_RUNLOCK                                124
#define SYS_RWLOCK_WLOCK                                  125
#define SYS_RWLOCK_WUNLOCK                                127
#define SYS_RWLOCK_TRYWLOCK                               148
#define SYSCALL_RWLOCK_CREATE                             SYS_RWLOCK_CREATE
#define SYSCALL_RWLOCK_DESTROY                            SYS_RWLOCK_DESTROY
#define SYSCALL_RWLOCK_RLOCK                              SYS_RWLOCK_RLOCK
#define SYSCALL_RWLOCK_TRYRLOCK                           SYS_RWLOCK_TRYRLOCK
#define SYSCALL_RWLOCK_RUNLOCK                            SYS_RWLOCK_RUNLOCK
#define SYSCALL_RWLOCK_WLOCK                              SYS_RWLOCK_WLOCK
#define SYSCALL_RWLOCK_WUNLOCK                            SYS_RWLOCK_WUNLOCK
#define SYSCALL_RWLOCK_TRYWLOCK                           SYS_RWLOCK_TRYWLOCK

#define SYS_EVENT_QUEUE_CREATE                            128
#define SYS_EVENT_QUEUE_DESTROY                           129
#define SYS_EVENT_QUEUE_RECEIVE                           130
#define SYS_EVENT_QUEUE_TRYRECEIVE                        131
#define SYS_EVENT_FLAG_CANCEL                             132
#define SYS_EVENT_QUEUE_DRAIN                             133
#define SYS_EVENT_PORT_CREATE                             134
#define SYS_EVENT_PORT_DESTROY                            135
#define SYS_EVENT_PORT_CONNECT_LOCAL                      136
#define SYS_EVENT_PORT_DISCONNECT                         137
#define SYS_EVENT_PORT_SEND                               138
#define SYS_EVENT_FLAG_GET                                139
#define SYS_EVENT_PORT_CONNECT_IPC                        140
#define SYS_EVENT_FLAG_SET_BIT                              8
#define SYS_EVENT_FLAG_SET_BIT_IMPATIENT                    9
#define SYS_EVENT_FLAG_CREATE                              82
#define SYS_EVENT_FLAG_DESTROY                             83
#define SYS_EVENT_FLAG_WAIT                                85
#define SYS_EVENT_FLAG_TRYWAIT                             86
#define SYS_EVENT_FLAG_SET                                 87
#define SYS_EVENT_FLAG_CLEAR                              118
#define SYSCALL_EVENT_QUEUE_CREATE                        SYS_EVENT_QUEUE_CREATE
#define SYSCALL_EVENT_QUEUE_DESTROY                       SYS_EVENT_QUEUE_DESTROY
#define SYSCALL_EVENT_QUEUE_RECEIVE                       SYS_EVENT_QUEUE_RECEIVE
#define SYSCALL_EVENT_QUEUE_TRYRECEIVE                    SYS_EVENT_QUEUE_TRYRECEIVE
#define SYSCALL_EVENT_FLAG_CANCEL                         SYS_EVENT_FLAG_CANCEL
#define SYSCALL_EVENT_QUEUE_DRAIN                         SYS_EVENT_QUEUE_DRAIN
#define SYSCALL_EVENT_PORT_CREATE                         SYS_EVENT_PORT_CREATE
#define SYSCALL_EVENT_PORT_DESTROY                        SYS_EVENT_PORT_DESTROY
#define SYSCALL_EVENT_PORT_CONNECT_LOCAL                  SYS_EVENT_PORT_CONNECT_LOCAL
#define SYSCALL_EVENT_PORT_DISCONNECT                     SYS_EVENT_PORT_DISCONNECT
#define SYSCALL_EVENT_PORT_SEND                           SYS_EVENT_PORT_SEND
#define SYSCALL_EVENT_FLAG_GET                            SYS_EVENT_FLAG_GET
#define SYSCALL_EVENT_PORT_CONNECT_IPC                    SYS_EVENT_PORT_CONNECT_IPC
#define SYSCALL_EVENT_FLAG_SET_BIT                        SYS_EVENT_FLAG_SET_BIT
#define SYSCALL_EVENT_FLAG_SET_BIT_IMPATIENT              SYS_EVENT_FLAG_SET_BIT_IMPATIENT
#define SYSCALL_EVENT_FLAG_CREATE                         SYS_EVENT_FLAG_CREATE
#define SYSCALL_EVENT_FLAG_DESTROY                        SYS_EVENT_FLAG_DESTROY
#define SYSCALL_EVENT_FLAG_WAIT                           SYS_EVENT_FLAG_WAIT
#define SYSCALL_EVENT_FLAG_TRYWAIT                        SYS_EVENT_FLAG_TRYWAIT
#define SYSCALL_EVENT_FLAG_SET                            SYS_EVENT_FLAG_SET
#define SYSCALL_EVENT_FLAG_CLEAR                          SYS_EVENT_FLAG_CLEAR

#define SYS_TIME_GET_CURRENT_TIME                         145
#define SYS_TIME_GET_TIMEBASE_FREQUENCY                   147
#define SYSCALL_TIME_GET_CURRENT_TIME                     SYS_TIME_GET_CURRENT_TIME
#define SYSCALL_TIME_GET_TIMEBASE_FREQUENCY               SYS_TIME_GET_TIMEBASE_FREQUENCY

#define SYS_RAW_SPU_CREATE_INTERRUPT_TAG                  150
#define SYS_RAW_SPU_SET_INT_MASK                          151
#define SYS_RAW_SPU_GET_INT_MASK                          152
#define SYS_RAW_SPU_SET_INT_STAT                          153
#define SYS_RAW_SPU_GET_INT_STAT                          154
#define SYS_RAW_SPU_CREATE                                160
#define SYS_RAW_SPU_DESTROY                               161
#define SYS_RAW_SPU_READ_PUINT_MB                         163
#define SYS_RAW_SPU_SET_SPU_CFG                           196
#define SYS_RAW_SPU_GET_SPU_CFG                           197
#define SYS_RAW_SPU_RECOVER_PAGE_FAULT                    199
#define SYSCALL_RAW_SPU_CREATE_INTERRUPT_TAG              SYS_RAW_SPU_CREATE_INTERRUPT_TAG
#define SYSCALL_RAW_SPU_SET_INT_MASK                      SYS_RAW_SPU_SET_INT_MASK
#define SYSCALL_RAW_SPU_GET_INT_MASK                      SYS_RAW_SPU_GET_INT_MASK
#define SYSCALL_RAW_SPU_SET_INT_STAT                      SYS_RAW_SPU_SET_INT_STAT
#define SYSCALL_RAW_SPU_GET_INT_STAT                      SYS_RAW_SPU_GET_INT_STAT
#define SYSCALL_RAW_SPU_CREATE                            SYS_RAW_SPU_CREATE
#define SYSCALL_RAW_SPU_DESTROY                           SYS_RAW_SPU_DESTROY
#define SYSCALL_RAW_SPU_READ_PUINT_MB                     SYS_RAW_SPU_READ_PUINT_MB
#define SYSCALL_RAW_SPU_SET_SPU_CFG                       SYS_RAW_SPU_SET_SPU_CFG
#define SYSCALL_RAW_SPU_GET_SPU_CFG                       SYS_RAW_SPU_GET_SPU_CFG
#define SYSCALL_RAW_SPU_RECOVER_PAGE_FAULT                SYS_RAW_SPU_RECOVER_PAGE_FAULT

#define SYS_SPU_IMAGE_OPEN                                156
#define SYS_SPU_INITIALIZE                                169
#define SYS_SPU_SYSTEM_MODULE_ID_INVALID 				  0xFFFFFFFFU
#define SYSCALL_SPU_IMAGE_OPEN                            SYS_SPU_IMAGE_OPEN
#define SYSCALL_SPU_INITIALIZE                            SYS_SPU_INITIALIZE
#define SYSCALL_SPU_SYSTEM_MODULE_ID_INVALID			  SYS_SPU_SYSTEM_MODULE_ID_INVALID

#define SYS_SPU_THREAD_GET_EXIT_STATUS                        165
#define SYS_SPU_THREAD_SET_ARGUMENT                           166
#define SYS_SPU_THREAD_GROUP_START_ON_EXIT                    167
#define SYS_SPU_THREAD_GROUP_CREATE                           170
#define SYS_SPU_THREAD_GROUP_DESTROY                          171
#define SYS_SPU_THREAD_INITIALIZE                             172
#define SYS_SPU_THREAD_GROUP_START                            173
#define SYS_SPU_THREAD_GROUP_SUSPEND                          174
#define SYS_SPU_THREAD_GROUP_RESUME                           175
#define SYS_SPU_THREAD_GROUP_YIELD                            176
#define SYS_SPU_THREAD_GROUP_TERMINATE                        177
#define SYS_SPU_THREAD_GROUP_JOIN                             178
#define SYS_SPU_THREAD_GROUP_SET_PRIORITY                     179
#define SYS_SPU_THREAD_GROUP_GET_PRIORITY                     180
#define SYS_SPU_THREAD_WRITE_LS                               181
#define SYS_SPU_THREAD_READ_LS                                182
#define SYS_SPU_THREAD_WRITE_SNR                              184
#define SYS_SPU_THREAD_GROUP_CONNECT_EVENT                    185
#define SYS_SPU_THREAD_GROUP_DISCONNECT_EVENT                 186
#define SYS_SPU_THREAD_SET_SPU_CFG                            187
#define SYS_SPU_THREAD_GET_SPU_CFG                            188
#define SYS_SPU_THREAD_WRITE_SPU_MB                           190
#define SYS_SPU_THREAD_CONNECT_EVENT                          191
#define SYS_SPU_THREAD_DISCONNECT_EVENT                       192
#define SYS_SPU_THREAD_BIND_QUEUE                             193
#define SYS_SPU_THREAD_UNBIND_QUEUE                           194
#define SYS_SPU_THREAD_GROUP_ID_INVALID  				      0xFFFFFFFFU
#define SYS_SPU_THREAD_ID_INVALID        				      0xFFFFFFFFU
#define SYS_SPU_THREAD_RECOVER_PAGE_FAULT                     198
#define SYS_SPU_THREAD_GROUP_SET_COOPERATIVE_VICTIMS          250
#define SYS_SPU_THREAD_GROUP_CONNECT_EVENT_ALL_THREADS        251
#define SYS_SPU_THREAD_GROUP_DISCONNECT_EVENT_ALL_THREADS     252
#define SYS_SPU_THREAD_GROUP_LOG                              254
#define SYS_SPU_IMAGE_OPEN_BY_FD                              260
#define SYS_SPU_THREAD_EXIT                                   1
#define SYS_SPU_THREAD_GROUP_EXIT                             2
#define SYS_SPU_THREAD_YIELD                                  3
#define SYS_SPU_THREAD_RECEIVE_EVENT                          4
#define SYS_SPU_THREAD_TRYRECEIVE_EVENT                       5
#define SYS_SPU_THREAD_SEND_EVENT                             6
#define SYS_SPU_THREAD_THROW_EVENT                            7
#define SYS_SPU_THREAD_SWITCH_TO_SYSTEM_MODULE			      10
#define SYSCALL_SPU_THREAD_GET_EXIT_STATUS                    SYS_SPU_THREAD_GET_EXIT_STATUS
#define SYSCALL_SPU_THREAD_SET_ARGUMENT                       SYS_SPU_THREAD_SET_ARGUMENT
#define SYSCALL_SPU_THREAD_GROUP_START_ON_EXIT                SYS_SPU_THREAD_GROUP_START_ON_EXIT
#define SYSCALL_SPU_THREAD_GROUP_CREATE                       SYS_SPU_THREAD_GROUP_CREATE
#define SYSCALL_SPU_THREAD_GROUP_DESTROY                      SYS_SPU_THREAD_GROUP_DESTROY
#define SYSCALL_SPU_THREAD_INITIALIZE                         SYS_SPU_THREAD_INITIALIZE
#define SYSCALL_SPU_THREAD_GROUP_START                        SYS_SPU_THREAD_GROUP_START
#define SYSCALL_SPU_THREAD_GROUP_SUSPEND                      SYS_SPU_THREAD_GROUP_SUSPEND
#define SYSCALL_SPU_THREAD_GROUP_RESUME                       SYS_SPU_THREAD_GROUP_RESUME
#define SYSCALL_SPU_THREAD_GROUP_YIELD                        SYS_SPU_THREAD_GROUP_YIELD
#define SYSCALL_SPU_THREAD_GROUP_TERMINATE                    SYS_SPU_THREAD_GROUP_TERMINATE
#define SYSCALL_SPU_THREAD_GROUP_JOIN                         SYS_SPU_THREAD_GROUP_JOIN
#define SYSCALL_SPU_THREAD_GROUP_SET_PRIORITY                 SYS_SPU_THREAD_GROUP_JOIN
#define SYSCALL_SPU_THREAD_GROUP_GET_PRIORITY                 SYS_SPU_THREAD_GROUP_GET_PRIORITY
#define SYSCALL_SPU_THREAD_WRITE_LS                           SYS_SPU_THREAD_WRITE_LS
#define SYSCALL_SPU_THREAD_READ_LS                            SYS_SPU_THREAD_READ_LS
#define SYSCALL_SPU_THREAD_WRITE_SNR                          SYS_SPU_THREAD_WRITE_SNR
#define SYSCALL_SPU_THREAD_GROUP_CONNECT_EVENT                SYS_SPU_THREAD_GROUP_CONNECT_EVENT
#define SYSCALL_SPU_THREAD_GROUP_DISCONNECT_EVENT             SYS_SPU_THREAD_GROUP_DISCONNECT_EVENT
#define SYSCALL_SPU_THREAD_SET_SPU_CFG                        SYS_SPU_THREAD_SET_SPU_CFG
#define SYSCALL_SPU_THREAD_GET_SPU_CFG                        SYS_SPU_THREAD_GET_SPU_CFG
#define SYSCALL_SPU_THREAD_WRITE_SPU_MB                       SYS_SPU_THREAD_WRITE_SPU_MB
#define SYSCALL_SPU_THREAD_CONNECT_EVENT                      SYS_SPU_THREAD_CONNECT_EVENT
#define SYSCALL_SPU_THREAD_DISCONNECT_EVENT                   SYS_SPU_THREAD_DISCONNECT_EVENT
#define SYSCALL_SPU_THREAD_BIND_QUEUE                         SYS_SPU_THREAD_BIND_QUEUE
#define SYSCALL_SPU_THREAD_UNBIND_QUEUE                       SYS_SPU_THREAD_UNBIND_QUEUE
#define SYSCALL_SPU_THREAD_GROUP_ID_INVALID  				  SYS_SPU_THREAD_GROUP_ID_INVALID
#define SYSCALL_SPU_THREAD_ID_INVALID        				  SYS_SPU_THREAD_ID_INVALID
#define SYSCALL_SPU_THREAD_RECOVER_PAGE_FAULT                 SYS_SPU_THREAD_RECOVER_PAGE_FAULT
#define SYSCALL_SPU_THREAD_GROUP_SET_COOPERATIVE_VICTIMS      SYS_SPU_THREAD_GROUP_SET_COOPERATIVE_VICTIMS
#define SYSCALL_SPU_THREAD_GROUP_CONNECT_EVENT_ALL_THREADS    SYS_SPU_THREAD_GROUP_CONNECT_EVENT_ALL_THREADS
#define SYSCALL_SPU_THREAD_GROUP_DISCONNECT_EVENT_ALL_THREADS SYS_SPU_THREAD_GROUP_DISCONNECT_EVENT_ALL_THREADS
#define SYSCALL_SPU_THREAD_GROUP_LOG                          SYS_SPU_THREAD_GROUP_LOG
#define SYSCALL_SPU_IMAGE_OPEN_BY_FD                          SYS_SPU_IMAGE_OPEN_BY_FD
#define SYSCALL_SPU_THREAD_EXIT                               SYS_SPU_THREAD_EXIT
#define SYSCALL_SPU_THREAD_GROUP_EXIT                         SYS_SPU_THREAD_GROUP_EXIT
#define SYSCALL_SPU_THREAD_YIELD                              SYS_SPU_THREAD_YIELD
#define SYSCALL_SPU_THREAD_RECEIVE_EVENT                      SYS_SPU_THREAD_RECEIVE_EVENT
#define SYSCALL_SPU_THREAD_TRYRECEIVE_EVENT                   SYS_SPU_THREAD_TRYRECEIVE_EVENT
#define SYSCALL_SPU_THREAD_SEND_EVENT                         SYS_SPU_THREAD_SEND_EVENT
#define SYSCALL_SPU_THREAD_THROW_EVENT                        SYS_SPU_THREAD_THROW_EVENT
#define SYSCALL_SPU_THREAD_SWITCH_TO_SYSTEM_MODULE			  SYS_SPU_THREAD_SWITCH_TO_SYSTEM_MODULE

#define SYS_VM_MEMORY_MAP                                 300
#define SYS_VM_UNMAP                                      301
#define SYS_VM_APPEND_MEMORY                              302
#define SYS_VM_RETURN_MEMORY                              303
#define SYS_VM_LOCK                                       304
#define SYS_VM_UNLOCK                                     305
#define SYS_VM_TOUCH                                      306
#define SYS_VM_FLUSH                                      307
#define SYS_VM_INVALIDATE                                 308
#define SYS_VM_STORE                                      309
#define SYS_VM_SYNC                                       310
#define SYS_VM_TEST                                       311
#define SYS_VM_GET_STATISTICS                             312
#define SYSCALL_VM_MEMORY_MAP                             SYS_VM_MEMORY_MAP
#define SYSCALL_VM_UNMAP                                  SYS_VM_UNMAP
#define SYSCALL_VM_APPEND_MEMORY                          SYS_VM_APPEND_MEMORY
#define SYSCALL_VM_RETURN_MEMORY                          SYS_VM_RETURN_MEMORY
#define SYSCALL_VM_LOCK                                   SYS_VM_LOCK
#define SYSCALL_VM_UNLOCK                                 SYS_VM_UNLOCK
#define SYSCALL_VM_TOUCH                                  SYS_VM_TOUCH
#define SYSCALL_VM_FLUSH                                  SYS_VM_FLUSH
#define SYSCALL_VM_INVALIDATE                             SYS_VM_INVALIDATE
#define SYSCALL_VM_STORE                                  SYS_VM_STORE
#define SYSCALL_VM_SYNC                                   SYS_VM_SYNC
#define SYSCALL_VM_TEST                                   SYS_VM_TEST
#define SYSCALL_VM_GET_STATISTICS                         SYS_VM_GET_STATISTICS

#define SYS_MEMORY_CONTAINER_CREATE                       324
#define SYS_MEMORY_CONTAINER_DESTROY                      325
#define SYS_MEMORY_CONTAINER_GET_SIZE                     343
#define SYS_MEMORY_ALLOCATE                               348
#define SYS_MEMORY_FREE                                   349
#define SYS_MEMORY_ALLOCATE_FROM_CONTAINER                350
#define SYS_MEMORY_GET_PAGE_ATTRIBUTE                     351
#define SYS_MEMORY_GET_USER_MEMORY_SIZE                   352
#define SYSCALL_MEMORY_CONTAINER_CREATE                   SYS_MEMORY_CONTAINER_CREATE
#define SYSCALL_MEMORY_CONTAINER_DESTROY                  SYS_MEMORY_CONTAINER_DESTROY
#define SYSCALL_MEMORY_CONTAINER_GET_SIZE                 SYS_MEMORY_CONTAINER_GET_SIZE
#define SYSCALL_MEMORY_ALLOCATE                           SYS_MEMORY_ALLOCATE
#define SYSCALL_MEMORY_FREE                               SYS_MEMORY_FREE
#define SYSCALL_MEMORY_ALLOCATE_FROM_CONTAINER            SYS_MEMORY_ALLOCATE_FROM_CONTAINER
#define SYSCALL_MEMORY_GET_PAGE_ATTRIBUTE                 SYS_MEMORY_GET_PAGE_ATTRIBUTE
#define SYSCALL_MEMORY_GET_USER_MEMORY_SIZE               SYS_MEMORY_GET_USER_MEMORY_SIZE

#define SYS_MMAPPER_ALLOCATE_FIXED_ADDRESS                326
#define SYS_MMAPPER_ENABLE_PAGE_FAULT_NOTIFICATION        327
#define SYS_MMAPPER_ALLOCATE_ADDRESS                      330
#define SYS_MMAPPER_FREE_ADDRESS                          331
#define SYS_MMAPPER_CHANGE_ADDRESS_ACCESS_RIGHT           336
#define SYS_MMAPPER_SEARCH_AND_MAP                        337
#define SYSCALL_MMAPPER_ALLOCATE_FIXED_ADDRESS            SYS_MMAPPER_ALLOCATE_FIXED_ADDRESS
#define SYSCALL_MMAPPER_ENABLE_PAGE_FAULT_NOTIFICATION    SYS_MMAPPER_ENABLE_PAGE_FAULT_NOTIFICATION
#define SYSCALL_MMAPPER_ALLOCATE_ADDRESS                  SYS_MMAPPER_ALLOCATE_ADDRESS
#define SYSCALL_MMAPPER_FREE_ADDRESS                      SYS_MMAPPER_FREE_ADDRESS
#define SYSCALL_MMAPPER_CHANGE_ADDRESS_ACCESS_RIGHT       SYS_MMAPPER_CHANGE_ADDRESS_ACCESS_RIGHT
#define SYSCALL_MMAPPER_SEARCH_AND_MAP                    SYS_MMAPPER_SEARCH_AND_MAP

#define SYS_TTY_READ                                      402
#define SYS_TTY_WRITE                                     403
#define SYSCALL_TTY_READ                                  SYS_TTY_READ
#define SYSCALL_TTY_WRITE                                 SYS_TTY_WRITE

#define SYS_PRX_GET_PPU_GUID                              467
#define SYSCALL_PRX_GET_PPU_GUID                          SYS_PRX_GET_PPU_GUID

#define SYS_OVERLAY_LOAD_MODULE                           450
#define SYS_OVERLAY_UNLOAD_MODULE                         451
#define SYS_OVERLAY_GET_MODULE_LIST                       452
#define SYS_OVERLAY_GET_MODULE_INFO                       453
#define SYS_OVERLAY_LOAD_MODULE_BY_FD                     454
#define SYS_OVERLAY_GET_MODULE_INFO2                      455
#define SYS_OVERLAY_GET_SDK_VERSION                       456
#define SYSCALL_OVERLAY_LOAD_MODULE                       SYS_OVERLAY_LOAD_MODULE
#define SYSCALL_OVERLAY_UNLOAD_MODULE                     SYS_OVERLAY_UNLOAD_MODULE
#define SYSCALL_OVERLAY_GET_MODULE_LIST                   SYS_OVERLAY_GET_MODULE_LIST
#define SYSCALL_OVERLAY_GET_MODULE_INFO                   SYS_OVERLAY_GET_MODULE_INFO
#define SYSCALL_OVERLAY_LOAD_MODULE_BY_FD                 SYS_OVERLAY_LOAD_MODULE_BY_FD
#define SYSCALL_OVERLAY_GET_MODULE_INFO2                  SYS_OVERLAY_GET_MODULE_INFO2
#define SYSCALL_OVERLAY_GET_SDK_VERSION                   SYS_OVERLAY_GET_SDK_VERSION

#define SYS_STORAGE_OPEN                                  600
#define SYS_STORAGE_CLOSE                                 601
#define SYS_STORAGE_READ                                  602
#define SYS_STORAGE_WRITE                                 603
#define SYS_STORAGE_SEND_DEVICE_COMMAND                   604
#define SYS_STORAGE_ASYNC_CONFIGURE                       605
#define SYS_STORAGE_ASYNC_READ                            606
#define SYS_STORAGE_ASYNC_WRITE                           607
#define SYS_STORAGE_ASYNC_CANCEL                          608
#define SYS_STORAGE_GET_DEVICE_INFO                       609
#define SYS_STORAGE_GET_DEVICE_CONFIG                     610
#define SYS_STORAGE_REPORT_DEVICES                        611
#define SYS_STORAGE_CONFIGURE_MEDIUM_EVENT                612
#define SYS_STORAGE_SET_MEDIUM_POLLING_INTERVAL           613
#define SYS_STORAGE_CREATE_REGION                         614
#define SYS_STORAGE_DELETE_REGION                         615
#define SYS_STORAGE_EXECUTE_DEVICE_COMMAND                616
#define SYS_STORAGE_GET_REGION_ACL                        617
#define SYS_STORAGE_SET_REGION_ACL                        618
#define SYS_STORAGE_ASYNC_SEND_DEVICE_COMMAND             619
#define SYS_STORAGE_GET_REGION_OFFSET                     622
#define SYS_STORAGE_SET_EMULATED_SPEED                    623
#define SYSCALL_STORAGE_OPEN                              SYS_STORAGE_OPEN
#define SYSCALL_STORAGE_CLOSE                             SYS_STORAGE_CLOSE
#define SYSCALL_STORAGE_READ                              SYS_STORAGE_READ
#define SYSCALL_STORAGE_WRITE                             SYS_STORAGE_WRITE
#define SYSCALL_STORAGE_SEND_DEVICE_COMMAND               SYS_STORAGE_SEND_DEVICE_COMMAND
#define SYSCALL_STORAGE_ASYNC_CONFIGURE                   SYS_STORAGE_ASYNC_CONFIGURE
#define SYSCALL_STORAGE_ASYNC_READ                        SYS_STORAGE_ASYNC_READ
#define SYSCALL_STORAGE_ASYNC_WRITE                       SYS_STORAGE_ASYNC_WRITE
#define SYSCALL_STORAGE_ASYNC_CANCEL                      SYS_STORAGE_ASYNC_CANCEL
#define SYSCALL_STORAGE_GET_DEVICE_INFO                   SYS_STORAGE_GET_DEVICE_INFO
#define SYSCALL_STORAGE_GET_DEVICE_CONFIG                 SYS_STORAGE_GET_DEVICE_CONFIG
#define SYSCALL_STORAGE_REPORT_DEVICES                    SYS_STORAGE_REPORT_DEVICES
#define SYSCALL_STORAGE_CONFIGURE_MEDIUM_EVENT            SYS_STORAGE_CONFIGURE_MEDIUM_EVENT
#define SYSCALL_STORAGE_SET_MEDIUM_POLLING_INTERVAL       SYS_STORAGE_SET_MEDIUM_POLLING_INTERVAL
#define SYSCALL_STORAGE_CREATE_REGION                     SYS_STORAGE_CREATE_REGION
#define SYSCALL_STORAGE_DELETE_REGION                     SYS_STORAGE_DELETE_REGION
#define SYSCALL_STORAGE_EXECUTE_DEVICE_COMMAND            SYS_STORAGE_EXECUTE_DEVICE_COMMAND
#define SYSCALL_STORAGE_GET_REGION_ACL                    SYS_STORAGE_GET_REGION_ACL
#define SYSCALL_STORAGE_SET_REGION_ACL                    SYS_STORAGE_SET_REGION_ACL
#define SYSCALL_STORAGE_ASYNC_SEND_DEVICE_COMMAND         SYS_STORAGE_ASYNC_SEND_DEVICE_COMMAND
#define SYSCALL_STORAGE_GET_REGION_OFFSET                 SYS_STORAGE_GET_REGION_OFFSET
#define SYSCALL_STORAGE_SET_EMULATED_SPEED                SYS_STORAGE_SET_EMULATED_SPEED

#define SYS_IO_BUFFER_CREATE                              624
#define SYS_IO_BUFFER_DESTROY                             625
#define SYS_IO_BUFFER_ALLOCATE                            626
#define SYS_IO_BUFFER_FREE                                627
#define SYSCALL_IO_BUFFER_CREATE                          SYS_IO_BUFFER_CREATE
#define SYSCALL_IO_BUFFER_DESTROY                         SYS_IO_BUFFER_DESTROY
#define SYSCALL_IO_BUFFER_ALLOCATE                        SYS_IO_BUFFER_ALLOCATE
#define SYSCALL_IO_BUFFER_FREE                            SYS_IO_BUFFER_FREE

#define SYS_GPIO_SET                                      630
#define SYS_GPIO_GET                                      631
#define SYSCALL_GPIO_SET                                  SYS_GPIO_SET
#define SYSCALL_GPIO_GET                                  SYS_GPIO_GET

#define SYS_FSW_CONNECT_EVENT                             633
#define SYS_FSW_DISCONNECT_EVENT                          634
#define SYSCALL_FSW_CONNECT_EVENT                         SYS_FSW_CONNECT_EVENT
#define SYSCALL_FSW_DISCONNECT_EVENT                      SYS_FSW_DISCONNECT_EVENT

#define SYS_RSX_DEVICE_OPEN                               666
#define SYS_RSX_DEVICE_CLOSE                              667
#define SYS_RSX_MEMORY_ALLOCATE                           668
#define SYS_RSX_MEMORY_FREE                               669
#define SYS_RSX_CONTEXT_ALLOCATE                          670
#define SYS_RSX_CONTEXT_FREE                              671
#define SYS_RSX_CONTEXT_IOMAP                             672
#define SYS_RSX_CONTEXT_IOUNMAP                           673
#define SYS_RSX_CONTEXT_ATTRIBUTE                         674
#define SYS_RSX_DEVICE_MAP                                675
#define SYS_RSX_DEVICE_UNMAP                              676
#define SYS_RSX_ATTRIBUTE                                 677
#define SYSCALL_RSX_DEVICE_OPEN                           SYS_RSX_DEVICE_OPEN
#define SYSCALL_RSX_DEVICE_CLOSE                          SYS_RSX_DEVICE_CLOSE
#define SYSCALL_RSX_MEMORY_ALLOCATE                       SYS_RSX_MEMORY_ALLOCATE
#define SYSCALL_RSX_MEMORY_FREE                           SYS_RSX_MEMORY_FREE
#define SYSCALL_RSX_CONTEXT_ALLOCATE                      SYS_RSX_CONTEXT_ALLOCATE
#define SYSCALL_RSX_CONTEXT_FREE                          SYS_RSX_CONTEXT_FREE
#define SYSCALL_RSX_CONTEXT_IOMAP                         SYS_RSX_CONTEXT_IOMAP
#define SYSCALL_RSX_CONTEXT_IOUNMAP                       SYS_RSX_CONTEXT_IOUNMAP
#define SYSCALL_RSX_CONTEXT_ATTRIBUTE                     SYS_RSX_CONTEXT_ATTRIBUTE
#define SYSCALL_RSX_DEVICE_MAP                            SYS_RSX_DEVICE_MAP
#define SYSCALL_RSX_DEVICE_UNMAP                          SYS_RSX_DEVICE_UNMAP
#define SYSCALL_RSX_ATTRIBUTE                             SYS_RSX_ATTRIBUTE

#define SYS_BDEMU_SEND_COMMAND                            699
#define SYSCALL_BDEMU_SEND_COMMAND                        SYS_BDEMU_SEND_COMMAND

#define SYS_SS_GET_OPEN_PSID                              872
#define SYSCALL_SS_GET_OPEN_PSID                          SYS_SS_GET_OPEN_PSID

#define SYS_DECI3_OPEN                                    880
#define SYS_DECI3_CREATE_EVENT_PATH                       881
#define SYS_DECI3_CLOSE                                   882
#define SYS_DECI3_SEND                                    883
#define SYS_DECI3_RECEIVE                                 884
#define SYSCALL_DECI3_OPEN                                SYS_DECI3_OPEN
#define SYSCALL_DECI3_CREATE_EVENT_PATH                   SYS_DECI3_CREATE_EVENT_PATH
#define SYSCALL_DECI3_CLOSE                               SYS_DECI3_CLOSE
#define SYSCALL_DECI3_SEND                                SYS_DECI3_SEND
#define SYSCALL_DECI3_RECEIVE                             SYS_DECI3_RECEIVE

#define _SYS_PRX_LOAD_MODULE                           480
#define _SYS_PRX_START_MODULE                          481
#define _SYS_PRX_STOP_MODULE                           482
#define _SYS_PRX_UNLOAD_MODULE                         483
#define _SYS_PRX_REGISTER_MODULE                       484
#define _SYS_PRX_QUERY_MODULE                          485
#define _SYS_PRX_REGISTER_LIBRARY                      486
#define _SYS_PRX_UNREGISTER_LIBRARY                    487
#define _SYS_PRX_LINK_LIBRARY                          488
#define _SYS_PRX_UNLINK_LIBRARY                        489
#define _SYS_PRX_QUERY_LIBRARY                         490
#define _SYS_PRX_GET_MODULE_LIST                       494
#define _SYS_PRX_GET_MODULE_INFO                       495
#define _SYS_PRX_GET_MODULE_ID_BY_NAME                 496
#define _SYS_PRX_LOAD_MODULE_ON_MEMCONTAINER           497
#define _SYS_PRX_START                                 498
#define _SYS_PRX_STOP                                  499
#define _SYS_PRX_GET_MODULE_ID_BY_ADDRESS              461
#define _SYS_PRX_LOAD_MODULE_BY_FD                     463
#define _SYS_PRX_LOAD_MODULE_ON_MEMCONTAINER_BY_FD     464
#define _SYS_PRX_LOAD_MODULE_LIST                      465
#define _SYS_PRX_LOAD_MODULE_LIST_ON_MEMCONTAINER      466
#define _SYSCALL_PRX_LOAD_MODULE                       _SYS_PRX_LOAD_MODULE
#define _SYSCALL_PRX_START_MODULE                      _SYS_PRX_START_MODULE
#define _SYSCALL_PRX_STOP_MODULE                       _SYS_PRX_STOP_MODULE
#define _SYSCALL_PRX_UNLOAD_MODULE                     _SYS_PRX_UNLOAD_MODULE
#define _SYSCALL_PRX_REGISTER_MODULE                   _SYS_PRX_REGISTER_MODULE
#define _SYSCALL_PRX_QUERY_MODULE                      _SYS_PRX_QUERY_MODULE
#define _SYSCALL_PRX_REGISTER_LIBRARY                  _SYS_PRX_REGISTER_LIBRARY
#define _SYSCALL_PRX_UNREGISTER_LIBRARY                _SYS_PRX_UNREGISTER_LIBRARY
#define _SYSCALL_PRX_LINK_LIBRARY                      _SYS_PRX_LINK_LIBRARY
#define _SYSCALL_PRX_UNLINK_LIBRARY                    _SYS_PRX_UNLINK_LIBRARY
#define _SYSCALL_PRX_QUERY_LIBRARY                     _SYS_PRX_QUERY_LIBRARY
#define _SYSCALL_PRX_GET_MODULE_LIST                   _SYS_PRX_GET_MODULE_LIST
#define _SYSCALL_PRX_GET_MODULE_INFO                   _SYS_PRX_GET_MODULE_INFO
#define _SYSCALL_PRX_GET_MODULE_ID_BY_NAME             _SYS_PRX_GET_MODULE_ID_BY_NAME
#define _SYSCALL_PRX_LOAD_MODULE_ON_MEMCONTAINER       _SYS_PRX_LOAD_MODULE_ON_MEMCONTAINER
#define _SYSCALL_PRX_START                             _SYS_PRX_START
#define _SYSCALL_PRX_STOP                              _SYS_PRX_STOP
#define _SYSCALL_PRX_GET_MODULE_ID_BY_ADDRESS          _SYS_PRX_GET_MODULE_ID_BY_ADDRESS
#define _SYSCALL_PRX_LOAD_MODULE_BY_FD                 _SYS_PRX_LOAD_MODULE_BY_FD
#define _SYSCALL_PRX_LOAD_MODULE_ON_MEMCONTAINER_BY_FD _SYS_PRX_LOAD_MODULE_ON_MEMCONTAINER_BY_FD
#define _SYSCALL_PRX_LOAD_MODULE_LIST                  _SYS_PRX_LOAD_MODULE_LIST
#define _SYSCALL_PRX_LOAD_MODULE_LIST_ON_MEMCONTAINER  _SYS_PRX_LOAD_MODULE_LIST_ON_MEMCONTAINER


#define SYS_SYNC_FIFO                 0x00001
#define SYS_SYNC_PRIORITY             0x00002
#define SYS_SYNC_PRIORITY_INHERIT     0x00003
#define SYS_SYNC_RETRY                0x00004
#define SYS_SYNC_RECURSIVE            0x00010
#define SYS_SYNC_NOT_RECURSIVE        0x00020
#define SYS_SYNC_NOT_PROCESS_SHARED   0x00200
#define SYS_SYNC_ADAPTIVE             0x01000
#define SYS_SYNC_NOT_ADAPTIVE         0x02000
#define SYS_SYNC_NEWLY_CREATED        0x00001
#define SYS_SYNC_NOT_CREATE           0x00002
#define SYS_SYNC_NOT_CARE             0x00003
#define SYS_SYNC_WAITER_SINGLE        0x10000
#define SYS_SYNC_WAITER_MULTIPLE      0x20000
#define SYS_NO_TIMEOUT                0x00
#define SYS_EVENT_FLAG_WAIT_AND       0x000001
#define SYS_EVENT_FLAG_WAIT_OR        0x000002
#define SYS_EVENT_FLAG_WAIT_CLEAR     0x000010
#define SYS_EVENT_FLAG_WAIT_CLEAR_ALL 0x000020
#define SYS_MUTEX_ID_INVALID          0xFFFFFFFFU
#define SYS_COND_ID_INVALID	          0xFFFFFFFFU
#define SYS_RWLOCK_ID_INVALID         0xFFFFFFFFU
#define SYS_SEMAPHORE_ID_INVALID      0xFFFFFFFFU
#define SYS_EVENT_FLAG_ID_INVALID     0xFFFFFFFFU
#define SYS_SYNC_NAME_LENGTH          7
#define SYS_SYNC_NAME_SIZE            (SYS_SYNC_NAME_LENGTH + 1)

#define SYS_DBG_PPU_THREAD_STOP						 0x0000000000000001ULL
#define SYS_DBG_SPU_THREAD_GROUP_STOP				 0x0000000000000002ULL
#define SYS_DBG_SYSTEM_PPU_THREAD_NOT_STOP			 0x0000000000000004ULL
#define SYS_DBG_SYSTEM_SPU_THREAD_GROUP_NOT_STOP	 0x0000000000000008ULL
#define SYS_DBG_NOT_EXE_CTRL_BY_COREDUMP_EVENT		 0x0000000000000010ULL
#define SYS_DBG_PPU_EXCEPTION_TRAP					 0x0000000001000000ULL
#define SYS_DBG_PPU_EXCEPTION_PREV_INST				 0x0000000002000000ULL
#define SYS_DBG_PPU_EXCEPTION_ILL_INST				 0x0000000004000000ULL
#define SYS_DBG_PPU_EXCEPTION_TEXT_HTAB_MISS		 0x0000000008000000ULL
#define SYS_DBG_PPU_EXCEPTION_TEXT_SLB_MISS			 0x0000000010000000ULL
#define SYS_DBG_PPU_EXCEPTION_DATA_HTAB_MISS		 0x0000000020000000ULL
#define SYS_DBG_PPU_EXCEPTION_DATA_SLB_MISS			 0x0000000040000000ULL
#define SYS_DBG_PPU_EXCEPTION_FLOAT					 0x0000000080000000ULL
#define SYS_DBG_PPU_EXCEPTION_DABR_MATCH			 0x0000000100000000ULL
#define SYS_DBG_PPU_EXCEPTION_ALIGNMENT				 0x0000000200000000ULL
#define SYS_DBG_PPU_EXCEPTION_DATA_MAT				 0x0000002000000000ULL
#define SYS_DBG_EVENT_CORE_DUMPED					 0x0000000000001000ULL
#define SYS_DBG_EVENT_PPU_EXCEPTION_HANDLER_SIGNALED 0x0000000000002000ULL

#define SYS_OVERLAY_ID_INVALID					0xffffffffU
#define SYS_OVERLAY_MAX_NUM_OF_SEGMENTS_IN_OVLM	4
#define SYS_OVERLAY_SEGMENT_INFO_INDEX_INVALID	0xffffffffU
#define SYS_OVERLAY_MODULE_FILENAME_SIZE 		CELL_FS_MAX_FS_PATH_LENGTH
#define SYS_OVERLAY_PARAM_VERSION_INVALID		0xffffffffU
#define SYS_OVERLAY_PARAM_VERSION_170_0			0x00017000U
#define SYS_OVERLAY_PARAM_MAGIC					0x4f564c4dU
#define SYS_OVERLAY_MODULE_NAME_SIZE            0x50U

#define SYS_PRX_RESIDENT			        0
#define SYS_PRX_NO_RESIDENT			        1
#define SYS_PRX_START_OK			        SYS_PRX_RESIDENT
#define SYS_PRX_STOP_SUCCESS		        0
#define SYS_PRX_STOP_OK				        SYS_PRX_STOP_SUCCESS
#define SYS_PRX_STOP_FAILED			        1
#define SYS_PRX_MODULE_FILENAME_SIZE        512
#define SYS_PRX_PROCESS_ELF_ID		        0
#define SYS_PRX_LIB_OPD_IMPORT              0x2000
#define SYS_PRX_R_PPC_ADDR32                1
#define SYS_PRX_R_PPC_ADDR16_LO             4
#define SYS_PRX_R_PPC_ADDR16_HI             5
#define SYS_PRX_R_PPC_ADDR16_HA             6
#define SYS_PRX_R_PPC64_ADDR32              SYS_PRX_R_PPC_ADDR32
#define SYS_PRX_R_PPC64_ADDR16_LO           SYS_PRX_R_PPC_ADDR16_LO
#define SYS_PRX_R_PPC64_ADDR16_HI           SYS_PRX_R_PPC_ADDR16_HI
#define SYS_PRX_R_PPC64_ADDR16_HA           SYS_PRX_R_PPC_ADDR16_HA
#define SYS_PRX_R_PPC64_ADDR64              38
#define SYS_PRX_VARLINK_TERMINATE32         0x00000000
#define SYS_PRX_LOAD_MODULE_FLAGS_VALIDMASK	0x0000000000000001
#define SYS_PRX_LOAD_MODULE_FLAGS_FIXEDADDR	0x0000000000000001

#define	SYS_PPU_THREAD_CREATE_JOINABLE	0x0000000000000001
#define	SYS_PPU_THREAD_CREATE_INTERRUPT	0x0000000000000002
#define SYS_PPU_THREAD_ID_INVALID		0xffffffffu

#define PPU_GPR_NUM	 32
#define PPU_FPR_NUM	 32
#define PPU_VR_NUM	 32
#define PPU_VR_WIDTH 16

#define SPU_GPR_NUM		  128
#define SPU_MFC_CQ_SR_NUM 96
#define SPU_GPR_WIDTH	  16
#define SPU_MB_NUM		  4
#define SPU_FPSCR_WIDTH	  16

#define RAW_SPU_OFFSET      0x00100000UL
#define RAW_SPU_LS_OFFSET   0x00000000UL
#define RAW_SPU_PROB_OFFSET 0x00040000UL

#define SOCK_STREAM	1
#define SOCK_DGRAM	2
#define SOCK_RAW	3
#define SOCK_DGRAM_P2P	6
#define SOCK_STREAM_P2P	10

#define SO_REUSEADDR	0x0004
#define SO_KEEPALIVE	0x0008
#define SO_BROADCAST	0x0020
#define SO_LINGER	0x0080
#define SO_OOBINLINE	0x0100
#define SO_REUSEPORT	0x0200
#define SO_ONESBCAST	0x0800
#define SO_USECRYPTO	0x1000
#define SO_USESIGNATURE	0x2000
#define SO_SNDBUF	0x1001
#define SO_RCVBUF	0x1002
#define SO_SNDLOWAT	0x1003
#define SO_RCVLOWAT	0x1004
#define SO_SNDTIMEO	0x1005
#define SO_RCVTIMEO	0x1006
#define SO_ERROR	0x1007
#define SO_TYPE		0x1008
#define SO_NBIO		0x1100
#define SO_TPPOLICY	0x1101

#define	SOL_SOCKET	0xffff

#define AF_UNSPEC		0
#define AF_LOCAL		1
#define AF_UNIX			AF_LOCAL
#define AF_INET			2
#define AF_IMPLINK		3
#define AF_PUP			4
#define AF_CHAOS		5
#define AF_NS			6
#define AF_ISO			7
#define AF_OSI			AF_ISO
#define AF_ECMA			8
#define AF_DATAKIT		9
#define AF_CCITT		10
#define AF_SNA			11
#define AF_DECnet		12
#define AF_DLI			13
#define AF_LAT			14
#define AF_HYLINK		15
#define AF_APPLETALK	16
#define AF_ROUTE		17
#define AF_LINK			18
#define AF_COIP			20
#define AF_CNT			21
#define AF_IPX			23
#define AF_INET6		24
#define AF_ISDN			26
#define AF_E164			AF_ISDN
#define AF_NATM			27
#define AF_ARP			28
#define AF_MAX			31
#define pseudo_AF_XTP	19
#define pseudo_AF_RTIP	22
#define pseudo_AF_PIP	25
#define pseudo_AF_KEY	29
#define pseudo_HDRCMPLT 30

#define	MSG_OOB			 0x1
#define	MSG_PEEK		 0x2
#define MSG_DONTROUTE	 0x4
#define MSG_EOR			 0x8
#define MSG_TRUNC		 0x10
#define MSG_CTRUNC		 0x20
#define	MSG_WAITALL		 0x40
#define	MSG_DONTWAIT	 0x80
#define MSG_BCAST		 0x100
#define MSG_MCAST		 0x200
#define MSG_USECRYPTO	 0x400
#define MSG_USESIGNATURE 0x800

#define SHUT_RD	  0
#define SHUT_WR	  1
#define SHUT_RDWR 2

#define CELL_FS_MAX_FS_PATH_LENGTH 		(1024)
#define CELL_FS_MAX_FS_FILE_NAME_LENGTH (255)
#define CELL_FS_MAX_MP_LENGTH      		(31)
#define CELL_FS_S_IFMT  				0170000
#define CELL_FS_S_IFDIR 				0040000
#define CELL_FS_S_IFREG 				0100000
#define CELL_FS_S_IFLNK 				0120000
#define CELL_FS_S_IFWHT 				0160000
#define CELL_FS_S_IRWXU 				0000700
#define CELL_FS_S_IRUSR 				0000400
#define CELL_FS_S_IWUSR 				0000200
#define CELL_FS_S_IXUSR 				0000100
#define CELL_FS_S_IRWXG 				0000070
#define CELL_FS_S_IRGRP 				0000040
#define CELL_FS_S_IWGRP 				0000020
#define CELL_FS_S_IXGRP 				0000010
#define CELL_FS_S_IRWXO 				0000007
#define CELL_FS_S_IROTH 				0000004
#define CELL_FS_S_IWOTH 				0000002
#define CELL_FS_S_IXOTH 				0000001
#define CELL_FS_OTH_CREATE_MODE_RW      (CELL_FS_S_IRWXO &~ CELL_FS_S_IXOTH)
#define CELL_FS_OTH_CREATE_MODE_RX      (CELL_FS_S_IRWXO &~ CELL_FS_S_IWOTH)
#define CELL_FS_DEFAULT_CREATE_MODE_1   CELL_FS_S_IRWXU
#define CELL_FS_DEFAULT_CREATE_MODE_2   (CELL_FS_S_IRUSR | CELL_FS_S_IWUSR)
#define CELL_FS_DEFAULT_CREATE_MODE_3   (CELL_FS_S_IRUSR | CELL_FS_S_IXUSR)
#define CELL_FS_DEFAULT_CREATE_MODE_4   CELL_FS_S_IRUSR
#define CELL_FS_DEFAULT_CREATE_MODE_5   (CELL_FS_S_IRWXU | CELL_FS_S_IRWXO)
#define CELL_FS_DEFAULT_CREATE_MODE_6   (CELL_FS_DEFAULT_CREATE_MODE_2 | CELL_FS_OTH_CREATE_MODE_RW)
#define CELL_FS_DEFAULT_CREATE_MODE_7   (CELL_FS_DEFAULT_CREATE_MODE_3 | CELL_FS_OTH_CREATE_MODE_RX)
#define CELL_FS_DEFAULT_CREATE_MODE_8   (CELL_FS_S_IRUSR | CELL_FS_S_IROTH)
#define CELL_FS_TYPE_UNKNOWN   			0
#define CELL_FS_TYPE_DIRECTORY 			1
#define CELL_FS_TYPE_REGULAR   			2
#define CELL_FS_TYPE_SYMLINK   			3
#define CELL_FS_O_CREAT        			000100
#define CELL_FS_O_EXCL         			000200
#define CELL_FS_O_TRUNC        			001000
#define CELL_FS_O_APPEND       			002000
#define CELL_FS_O_ACCMODE      			000003
#define CELL_FS_O_RDONLY 				000000
#define CELL_FS_O_RDWR   				000002
#define CELL_FS_O_WRONLY 				000001
#define CELL_FS_O_MSELF		   			010000
#define CELL_FS_SEEK_SET 				SEEK_SET
#define CELL_FS_SEEK_CUR 				SEEK_CUR
#define CELL_FS_SEEK_END 				SEEK_END
#define CELL_FS_OK                  CELL_OK
#define CELL_FS_ERROR_EDOM          EDOM
#define CELL_FS_ERROR_EFAULT        EFAULT
#define CELL_FS_ERROR_EFBIG         EFBIG
#define CELL_FS_ERROR_EFPOS         EFPOS
#define CELL_FS_ERROR_EMLINK        EMLINK
#define CELL_FS_ERROR_ENFILE        ENFILE
#define CELL_FS_ERROR_ENOENT        ENOENT
#define CELL_FS_ERROR_ENOSPC        ENOSPC
#define CELL_FS_ERROR_ENOTTY        ENOTTY
#define CELL_FS_ERROR_EPIPE         EPIPE
#define CELL_FS_ERROR_ERANGE        ERANGE
#define CELL_FS_ERROR_EROFS         EROFS
#define CELL_FS_ERROR_ESPIPE        ESPIPE
#define CELL_FS_ERROR_E2BIG         E2BIG
#define CELL_FS_ERROR_EACCES        EACCES
#define CELL_FS_ERROR_EAGAIN        EAGAIN
#define CELL_FS_ERROR_EBADF         EBADF
#define CELL_FS_ERROR_EBUSY         EBUSY
#define CELL_FS_ERROR_ECHILD        ECHILD
#define CELL_FS_ERROR_EEXIST        EEXIST
#define CELL_FS_ERROR_EINTR         EINTR
#define CELL_FS_ERROR_EINVAL        EINVAL
#define CELL_FS_ERROR_EIO           EIO
#define CELL_FS_ERROR_EISDIR        EISDIR
#define CELL_FS_ERROR_EMFILE        EMFILE
#define CELL_FS_ERROR_ENODEV        ENODEV
#define CELL_FS_ERROR_ENOEXEC       ENOEXEC
#define CELL_FS_ERROR_ENOMEM        ENOMEM
#define CELL_FS_ERROR_ENOTDIR       ENOTDIR
#define CELL_FS_ERROR_ENXIO         ENXIO
#define CELL_FS_ERROR_EPERM         EPERM
#define CELL_FS_ERROR_ESRCH         ESRCH
#define CELL_FS_ERROR_EXDEV         EXDEV
#define CELL_FS_ERROR_EBADMSG       EBADMSG
#define CELL_FS_ERROR_ECANCELED     ECANCELED
#define CELL_FS_ERROR_EDEADLK       EDEADLK
#define CELL_FS_ERROR_EILSEQ        EILSEQ
#define CELL_FS_ERROR_EINPROGRESS   EINPROGRESS
#define CELL_FS_ERROR_EMSGSIZE      EMSGSIZE
#define CELL_FS_ERROR_ENAMETOOLONG  ENAMETOOLONG
#define CELL_FS_ERROR_ENOLCK        ENOLCK
#define CELL_FS_ERROR_ENOSYS        ENOSYS
#define CELL_FS_ERROR_ENOTEMPTY     ENOTEMPTY
#define CELL_FS_ERROR_ENOTSUP       ENOTSUP
#define CELL_FS_ERROR_ETIMEDOUT     ETIMEDOUT
#define CELL_FS_ERROR_EFSSPECIFIC   EFSSPECIFIC
#define CELL_FS_ERROR_EOVERFLOW     EOVERFLOW
#define CELL_FS_ERROR_ENOTMOUNTED   ENOTMOUNTED
#define CELL_FS_ERROR_ENOTMSELF     ENOTMSELF
#define CELL_FS_ERROR_ENOTSDATA     ENOTSDATA
#define CELL_FS_ERROR_EAUTHFATAL    EAUTHFATAL
#define CELL_FS_SUCCEEDED     		CELL_FS_OK
#define CELL_FS_EDOM          		CELL_FS_ERROR_EDOM
#define CELL_FS_EFAULT        		CELL_FS_ERROR_EFAULT
#define CELL_FS_EFBIG         		CELL_FS_ERROR_EFBIG
#define CELL_FS_EFPOS         		CELL_FS_ERROR_EFPOS
#define CELL_FS_EMLINK        		CELL_FS_ERROR_EMLINK
#define CELL_FS_ENFILE        		CELL_FS_ERROR_ENFILE
#define CELL_FS_ENOENT        		CELL_FS_ERROR_ENOENT
#define CELL_FS_ENOSPC        		CELL_FS_ERROR_ENOSPC
#define CELL_FS_ENOTTY        		CELL_FS_ERROR_ENOTTY
#define CELL_FS_EPIPE         		CELL_FS_ERROR_EPIPE
#define CELL_FS_ERANGE        		CELL_FS_ERROR_ERANGE
#define CELL_FS_EROFS         		CELL_FS_ERROR_EROFS
#define CELL_FS_ESPIPE        		CELL_FS_ERROR_ESPIPE
#define CELL_FS_E2BIG         		CELL_FS_ERROR_E2BIG
#define CELL_FS_EACCES        		CELL_FS_ERROR_EACCES
#define CELL_FS_EAGAIN        		CELL_FS_ERROR_EAGAIN
#define CELL_FS_EBADF         		CELL_FS_ERROR_EBADF
#define CELL_FS_EBUSY         		CELL_FS_ERROR_EBUSY
#define CELL_FS_ECHILD        		CELL_FS_ERROR_ECHILD
#define CELL_FS_EEXIST        		CELL_FS_ERROR_EEXIST
#define CELL_FS_EINTR         		CELL_FS_ERROR_EINTR
#define CELL_FS_EINVAL        		CELL_FS_ERROR_EINVAL
#define CELL_FS_EIO           		CELL_FS_ERROR_EIO
#define CELL_FS_EISDIR        		CELL_FS_ERROR_EISDIR
#define CELL_FS_EMFILE        		CELL_FS_ERROR_EMFILE
#define CELL_FS_ENODEV        		CELL_FS_ERROR_ENODEV
#define CELL_FS_ENOEXEC       		CELL_FS_ERROR_ENOEXEC
#define CELL_FS_ENOMEM        		CELL_FS_ERROR_ENOMEM
#define CELL_FS_ENOTDIR       		CELL_FS_ERROR_ENOTDIR
#define CELL_FS_ENXIO         		CELL_FS_ERROR_ENXIO
#define CELL_FS_EPERM         		CELL_FS_ERROR_EPERM
#define CELL_FS_ESRCH         		CELL_FS_ERROR_ESRCH
#define CELL_FS_EXDEV         		CELL_FS_ERROR_EXDEV
#define CELL_FS_EBADMSG       		CELL_FS_ERROR_EBADMSG
#define CELL_FS_ECANCELED     		CELL_FS_ERROR_ECANCELED
#define CELL_FS_EDEADLK       		CELL_FS_ERROR_EDEADLK
#define CELL_FS_EILSEQ        		CELL_FS_ERROR_EILSEQ
#define CELL_FS_EINPROGRESS   		CELL_FS_ERROR_EINPROGRESS
#define CELL_FS_EMSGSIZE      		CELL_FS_ERROR_EMSGSIZE
#define CELL_FS_ENAMETOOLONG  		CELL_FS_ERROR_ENAMETOOLONG
#define CELL_FS_ENOLCK        		CELL_FS_ERROR_ENOLCK
#define CELL_FS_ENOSYS        		CELL_FS_ERROR_ENOSYS
#define CELL_FS_ENOTEMPTY     		CELL_FS_ERROR_ENOTEMPTY
#define CELL_FS_ENOTSUP       		CELL_FS_ERROR_ENOTSUP
#define CELL_FS_ETIMEDOUT     		CELL_FS_ERROR_ETIMEDOUT
#define CELL_FS_EFSSPECIFIC   		CELL_FS_ERROR_EFSSPECIFIC
#define CELL_FS_EOVERFLOW     		CELL_FS_ERROR_EOVERFLOW
#define CELL_FS_ENOTMOUNTED   		CELL_FS_ERROR_ENOTMOUNTED
#define CELL_FS_ENOTMSELF     		CELL_FS_ERROR_ENOTMSELF
#define CELL_FS_ENOTSDATA     		CELL_FS_ERROR_ENOTSDATA
#define CELL_FS_EAUTHFATAL    		CELL_FS_ERROR_EAUTHFATAL

#define NO_UID 	   (-1)
#define NO_GID 	   (-1)
#define SYSTEM_UID (0)

#endif